### ISSUE TITLE
TelloLib Update

### ISSUE THREAD

**Issue by carter-james89** [comoc/TelloForUnity#5]
First off, let me say, thanks a lot for this. I'm a unity developer and I have all sorts of plans for my tello in Unity. This project is great and already has me flying around with my rift and thrustmaster joystick. That said, I really need the most recent version of tellolib.

I need the positional data that has been added to flight data since you created this. Vel,pos, and quat. I've tried a couple different things to accomplish this on my own.

I've tried creating my own unity project which does not motify tellolib, but can't figure out the NAL decoding after you get the frame. It would be nice to keep up with the tellolib updates without having to make changes to tello.cs every time.

I'm currently trying to update tellolib in this repo myself, but I think it would be much quicker you could do it, seeing as you already know how it works. Essentially I'm trying to duplicate your changes with the newest version.

My last option is going to be to try and add the new tellolib changes into this repo, instead of trying to replace the whole thing.

Edit:

Ok so I got it working with the newest version of telloLib working with video. Instead of using Tello.Start/Stop I just called Tello.startConnecting and everything works just fine. Curious why you started the task in a separate function, and what heartbeat and updatelisteners are for

**Comment by joshferns** [comment]
Hi @carter-james89  how did you update tothe newest version of TelloLib?
Did you just replace the CRC.cs, Tello.cs and UDP.cs scripts? Did the video work out of the box?

Thanks

**Comment by carter-james89** [comment]
Yeah I just replaced the whole tellolib folder, but unfortunately it will not work without some modifications to tello.cs/tellocontroller.cs.  

@comoc  seems to be controlling the thread processes himself, I assume because they will continue to run in the editor after you exit play mode. However I have gotten it to work by making disconnect() public, and just calling that OnApplicationQuit(); That means even via my method, tello.cs must be changed, albeit only line. I'm sure a request to the tellolib dev could get that function made public.

As far as I can tell, we are doing the same thing in different ways, but I may be wrong about that. I'm not 100% the reasoning behind comocs original changes regarding Start()/Stop() & updateHeartbeat().  

I'll wait a day or two for comocs input, else just upload my project.

**Comment by comoc** [comment]
Hey guys,

Thank you for checking.
I'm trying to integrate the latest TelloLib right now.
And I am expecting that it will takes about 3-4 days.
@carter-james89 Could you share your project? I'd like to refer your implementations.

Thanks

**Comment by carter-james89** [comment]
Here's my project. The only thing left of yours @comoc is the video streaming. I'd love to know your reasoning for using SingletonMonobehavior / the functions you added to Tello.cs. I eliminated the SMB inheritance and interacted with Tello.cs via startConnecting() and Disconnect().

My project has oculus rift/touch support, and all keyboard inputs go through the input manager. Let me know if you have any questions.

Please read the readme and know this is barely tested.

TelloLib-For-Unity(https://github.com/carter-james89/TelloLib-for-Unity)

**Comment by carter-james89** [comment]
@comoc Thanks a lot for the update. I have a ton of plans for this but I need a stable platform first. The project I posted above works, but the editor crashes every 7 or so plays. It has to to with unity destroying the tello plugin on play I'm pretty sure.

Anyway I'm trying to install your newest version but I'm getting this error about the plugin. Curious how I'm supposed to install this. Last time it only worked when I imported the plugin. Am I supposed to do something with TelloVideoDecoder?

![2018-09-10 20_41_46-unity 2018 2 4f1 personal 64bit - master unity - tellounitydemo - pc mac li](https://user-images.githubusercontent.com/18366302/45333245-c1dcbe00-b53a-11e8-9106-033599868d19.png)

**Comment by comoc** [comment]
Hi @carter-james89.  Thanks for trying.
I checked my Unity project and changed the DLL import settings.
I pushed above changes into the master branch.
Could you try it again?
Thanks,

**Comment by carter-james89** [comment]
> Hi @carter-james89. Thanks for trying.
> I checked my Unity project and changed the DLL import settings.
> I pushed above changes into the master branch.
> Could you try it again?
> Thanks,

Still no luck. Again all I'm doing is pulling  a fresh copy of the repo and trying to open TelloUnityDemo as a unity project. (with the tellolib fork) 

Also I can't open my fork locally because git says I don't have permission. Do you have to enable something for me to access my fork?
![2018-09-11 17_24_17-window](https://user-images.githubusercontent.com/18366302/45391408-6b2dbd80-b5e8-11e8-86f5-6a4421a7254b.png)

**Comment by comoc** [comment]
Could you check the following settings. (for Editor)
The CPU and OS settings should be x86_64 and Windows.
![image](https://user-images.githubusercontent.com/843396/45401000-a7652a80-b689-11e8-8650-df0e5fbf816e.png)

Otherwise,

**Comment by comoc** [comment]
Oh, I see.
The TelloVideoDecoder.dll whch I've pushed was a debug version. I think it is the cause.
Now I pushed its release version.
Could you try it again?
Thanks,

**Comment by comoc** [comment]
Hi @joshferns 

TelloForUnity the main Unity project. And the TelloForUnity is depending on TelloLib.

**Comment by joshferns** [comment]
Hi.
I'm still getting the error
![screenshot 381](https://user-images.githubusercontent.com/5207732/45424771-23c13300-b6b5-11e8-9134-6c20e042fe18.png)

**Comment by carter-james89** [comment]
![2018-09-12 08_48_08-tellounitydemo](https://user-images.githubusercontent.com/18366302/45429445-f3ec3e00-b668-11e8-8e79-e2b239c5eeae.png)

**Comment by joshferns** [comment]
Okay, I re-downloaded the whole project, now the dll  is 400 kb
and it seems to work without any errors

**Comment by comoc** [comment]
@joshferns
Many thanks!

 >  I've noticed that the .dll in your repo is only 1KB,
Oh, that's it!

I started to use Git LFS to manage dll files, But I think you are not using the LFS.
So I have just pushed every dlls without LFS again.

Could you try to pull them and check the size of TelloVideoDecoder.dll one more time? The size should be 400KB.

**Comment by joshferns** [comment]
@comoc  Yes It works now.
Yesterday I downloaded the zip directly from the github website, today I cloned the repo using sourcetree, I guess sourcetree resolved the LFS issue.

Thanks a lot.

**Comment by comoc** [comment]
Thank you so much @joshferns and @carter-james89 !
